#!/bin/bash -e

case "$1" in
    configure|upgrade)

        if getent passwd ceo > /dev/null; then
            CEO=ceo
            SUID=4750
            SUIDALL=4755
        else
            CEO=root
            SUID=755
            SUIDALL=755
        fi

        if getent group office > /dev/null; then
            OFFICE=office
        else
            OFFICE=root
        fi

        if ! dpkg-statoverride --list /usr/bin/ceo > /dev/null; then
            dpkg-statoverride --add --update $CEO $OFFICE $SUID /usr/bin/ceo
        fi

        if ! dpkg-statoverride --list /usr/bin/addhomedir > /dev/null; then
            dpkg-statoverride --add --update root $OFFICE $SUID /usr/bin/addhomedir
        fi

        if ! dpkg-statoverride --list /usr/bin/addmember > /dev/null; then
            dpkg-statoverride --add --update root $OFFICE $SUID /usr/bin/addmember
        fi

        if ! dpkg-statoverride --list /usr/bin/addclub > /dev/null; then
            dpkg-statoverride --add --update root $OFFICE $SUID /usr/bin/addclub
        fi

        if ! dpkg-statoverride --list /usr/bin/ceoquery > /dev/null; then
            dpkg-statoverride --add --update root root 755 /usr/bin/ceoquery
        fi

        if ! dpkg-statoverride --list /usr/bin/csc-chsh > /dev/null; then
            dpkg-statoverride --add --update $CEO root $SUIDALL /usr/bin/csc-chsh
        fi

        if ! dpkg-statoverride --list /usr/bin/csc-chfn > /dev/null; then
            dpkg-statoverride --add --update $CEO root $SUIDALL /usr/bin/csc-chfn
        fi

        if [ -f /etc/csc/ldap.cf ] && ! dpkg-statoverride --list /etc/csc/ldap.cf > /dev/null; then
            dpkg-statoverride --add --update $CEO staff 640 /etc/csc/ldap.cf
        fi
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
        echo "postinst called with unknown argument \"$1\"" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
