#!/bin/bash -e

case "$1" in
    purge)

        if dpkg-statoverride --list /usr/bin/ceo > /dev/null; then
            dpkg-statoverride --remove /usr/bin/ceo || true
        fi

        if dpkg-statoverride --list /usr/bin/addhomedir > /dev/null; then
            dpkg-statoverride --remove /usr/bin/addhomedir || true
        fi

        if dpkg-statoverride --list /usr/bin/ceoquery > /dev/null; then
            dpkg-statoverride --remove /usr/bin/ceoquery || true
        fi

        if dpkg-statoverride --list /etc/csc/ldap.cf > /dev/null; then
            dpkg-statoverride --remove /etc/csc/ldap.cf || true
        fi
        
        if dpkg-statoverride --list /etc/csc/ceo.keytab > /dev/null; then
            dpkg-statoverride --remove /etc/csc/ceo.keytab || true
        fi

        rmdir --ignore-fail-on-non-empty /etc/csc
            
    ;;
    
    remove|failed-upgrade|upgrade)
    ;;
    
    *)
        echo "postrm called with invalid argument \"$1\"" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
