#!/bin/bash -p

# This is a privileged script.
IFS=$' \t\n'
PATH=/usr/bin:/bin
unset ENV BASH_ENV CDPATH
umask 077

cd `dirname $0`

export CEO_PROG="$1" CEO_AUTH="$2" CEO_USER="$3" CEO_NAME="$4" CEO_DEPT="$5" CEO_STATUS="$6"
export CEO_OUTPUT="$(cat)"
run-parts --umask=077 new-member.d
