.TH ADDCLUB 1 "December 16, 2007"
.SH NAME
addclub \- add club accounts to the directory
.SH SYNOPSIS
.B addclub
userid clubname
.SH DESCRIPTION
.B Addclub
creates an LDAP entry and home directory for new club accounts.
.SH SEE ALSO
.BR ceo (1).
.SH AUTHOR
Michael Spang <mspang@csclub.uwaterloo.ca>
