.TH CEO 1 "December 16, 2007"
.SH NAME
ceo \- CSC Electronic Office
.SH DESCRIPTION
CSC Electronic Office is used to manage membership registration and
user accounts for the Computer Science Club. It has a graphical
user interface, started by typing
.B ceo
with no arguments.
.PP
.SH SEE ALSO
.BR addmember (1),
.BR addclub (1).
.SH AUTHORS
Michael Spang <mspang@csclub.uwaterloo.ca>
.br
David Bartley <dtbartle@csclub.uwaterloo.ca>
