#!/bin/bash -p

# This is a privileged script.
IFS=$' \t\n'
PATH=/usr/bin:/bin
unset ENV BASH_ENV CDPATH
umask 077

prog=$CEO_PROG
auth=$CEO_AUTH

tmp="$(tempfile)"
trap "rm $tmp" 0
exec >"$tmp"

authrn="$(getent passwd "$auth" | awk -F: '{ print $5 }' | sed -e 's/,.*//')"

h_from="$prog <ceo+$prog@csclub.uwaterloo.ca>"
h_to="Membership and Accounts <ceo@csclub.uwaterloo.ca>"
h_cc="$authrn <$auth@csclub.uwaterloo.ca>"

if test "$prog" = addmember; then
    user="$CEO_USER" name="$CEO_NAME" dept="$CEO_DEPT" status="$CEO_STATUS"
    subj="New Member: $user"
    test -z "$dept" && dept="things unknown"
    body="Name: $name
Account: $user
Program: $dept
Added by: $auth"

elif test "$prog" = addclub; then
    user="$CEO_USER" name="$CEO_NAME" status="$CEO_STATUS"
    subj="New Club Account: $user"
    body="Club: $name
Account: $user
Added by: $auth"

else
    exit 1
fi

output="$CEO_OUTPUT"

if test "$status" = "failure"; then
  subj="$subj (FAILURES)"
fi

echo "From: $h_from"
echo "To: $h_to"
echo "Cc: $h_cc"
echo "X-Auth-User: $auth"
echo "X-New-User: $user"
echo "X-New-Name: $name"
echo "Subject: $subj"
echo
echo "$body" | fmt -s
echo

if test "$status" = "success"; then
    echo all failures went undetected
elif test -n "$output"; then
    echo "$output"
fi

echo
echo Your Friend,
echo "$prog"

exec >&2
env - /usr/sbin/sendmail -t -f "ceo@csclub.uwaterloo.ca" < "$tmp"
